spring.application.name=cliente

# 1. Configuración del Servidor (Independencia)
# Se usa el puerto 8081 para Clientes para evitar conflictos
server.port=8081

# 2. Configuración Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_clientes?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=C4dpeafg**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de JPA
# 'update' permite que Hibernate cree/actualice las tablas automáticamente según las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Logs Estructurados
# Permite ver eventos de creación, errores y validaciones de la consola
loggin.level.org.springframework.web=INFO
loggin.level.cl.duoc.msclientes=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# 5. Formato de Respuestas JSON
spring.jackson.serialization.indent_output=true

spring.liquibase.enabled=false

